language: node_js
node_js:
  - lts/*
services:
  - mongodb
cache: npm
branches:
  only:
    - main
script:
  - npm run lint
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: 'bd528589-0e9e-4d3e-89b1-084685f7b34f'
